---
title: "Using the rightSidebar"
author: "David Granjon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## The rightSidebar

The most interesting feature of this package is the `rightSidebar()`. This concept was
not implemented (in R) in ygdashboard (pure HTML), that's why I translated 
the corresponding HTML code to R. To use it, you will have to replace `dashboardPage()`
by `dashboardPagePlus()` and `dashboardHeader()` by `dashboardHeaderPlus()`. Creating this
two additional functions let you choose whether you want to use this extra sidebar or not.

The template below will create the most basic shinydashboardPlus page:

```r
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
shinyApp(
  ui = dashboardPagePlus(
    header = dashboardHeaderPlus(
     enable_rightsidebar = TRUE,
     rightSidebarIcon = "gears"
    ),
    sidebar = dashboardSidebar(),
    body = dashboardBody(),
    rightsidebar = rightSidebar(),
    title = "DashboardPage"
  ),
  server = function(input, output) { }
)
```

The rightSidebar function takes the following arguments:

- background: you can display it either in light or dark mode
- `rightSidebarTabList()` will create a menu for your tabPanels. Populate it with
`rightSidebarTabItem()`, with a **unique id** and icons
- `rightSidebarPanel()` is the body of your panels. Fill it with `rightSidebarTabContent()`,
which id should be the same as in the `rightSidebarTabItem()`. You can include inputs,
text or custom HTML elements.
- in the `dashboardHeaderPlus()` function, you can customize the sidebar trigger.

```r
rightSidebar(
 background = "dark",
  rightSidebarTabList(
   rightSidebarTabItem(
    id = 1,
    icon = "desktop",
    active = TRUE
   ),
   rightSidebarTabItem(
    id = 2
   ),
   rightSidebarTabItem(
    id = 3,
    icon = "paint-brush"
   )
  ),
  rigthSidebarPanel(
   rightSidebarTabContent(
    id = 1,
    active = TRUE,
    title = "Tab 1",
    sliderInput(
     "obs", 
     "Number of observations:",
      min = 0, max = 1000, value = 500
     )
   ),
   rightSidebarTabContent(
    id = 2,
    title = "Tab 2",
    textInput("caption", "Caption", "Data Summary")
   ),
   rightSidebarTabContent(
    id = 3,
    title = "Tab 3",
    numericInput("obs", "Observations:", 10, min = 1, max = 100)
   )
  )
)
```

**WARNINGS**: there is a limitation of a maximum of **5** `rightSidebarTabItem()` in the
`rightSidebarTabList()`! This makes sense since above, the rightSidebar would not
be easy to use.